# !/usr/bin/env python3

print('<'"!DOCTYPE html"'>')
print('<'"html"'>')
print('<'"head"'>')
print('\t''<'"link rel="'"'"stylesheet"'"'" href=" '"' "../website/style.css" '"''>')
print('<'"/head"'>')
print('<'"title"'>'"CGI-result"'<'"/title"'>')
print('\t''<'"body bgcolor="'"'"#c0c0c0"'"''>')
print('\t''\t''<'"div"'>')
print('\t''\t''<'"br"'>')
print('\t''\t''<'"center"'>')
print()
print('\t''\t''<'"/center"'>')
print('\t''\t''<'"/div"'>')
print('\t''<'"/body"'>')
print('<'"html"'>')
